name: Waether data for Athenry from Met Éireann

on:
  schedule:
    - cron: '0 10 * * *' # Runs every day at 10 am
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write # Allows push access to the repository

jobs:
  fortune-cowsay:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Execute the Python script to get the weather data
    - name: Data pull
      run: |
        ./weather.sh 

    # Step 3: Run fortune and cowsay, and save the output to a timestamped file
    - name: Run fortune and cowsay
      run: |
        mkdir -p data/fortunes
        fortune | cowsay > data/fortunes/`date +"%Y%m%d_%H%M%S".txt`

    # Step 4: Commit and push the changes
    - name: Commit and Push
      env:
        TIMESTAMP: ${{ steps.run-fortune-cowsay.outputs.timestamp }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Added daily weather data: `"%Y%m%d_%H%M%S`"
        git push